server:
  port: 80
spring:
  rabbitmq:
    host: 192.168.3.16
    port: 5672
    username: admins
    password: admin
    listener:
      simple:
        acknowledge-mode: auto
        max-concurrency: 10
        concurrency: 10
        prefetch: 10
